Feat/renew access token
helsingborg-stad/helsingborg-io-sls-api pull request #134
Opened 2021-01-13 12:24 UTC by TeddyAndersson

## Explain the changes you’ve made

Support for variants of OAuth 2 Authorization Code Grant and Refresh Token Grant standards for obtaining tokens.

## Explain why these changes are made
The reason behind these changes are a need for clients to extend sessions by obtaining a new access token. This was currently not supported in the authorization/authentication flow provided by the api.

## Explain your solution
This new solution for obtaining tokens are dependent on what Oauth calls grant types. In order to specifiy a grant type and other params that needs to be passed query string params are used. The query string parameters passed with the request are then validated on the passed gran type and additional required params for that specific grant type. The solution currently supports two grant types authorization_code and refresh_token. 

Example of authorization_code grant: 
```?grant_type=authorization_code&code=valid_authorization_code```.
A valid authorization code can be obtained in the payload after a successfull login with bankid.

Example of refresh_token grant: 
```?grant_type=refresh_token&refresh_token=valid_refresh_token```.

Both grant types returns a response containing a pair of access and refresh token.

## How to test the changes?

In order to test these changes you will first need to add the appropriate secrets in AWS secrets manager. The naming of the secrets can be found in the config.js

*Test authorization code grant:*
1. create a token that has minimum payload of personalNumber and sign it with the authorization code secret defined in aws secrets manager. I suggest that you use jwt.io to generate a signed token.
2. Make a post request to https://your_aws_env_url/dev/auth/token?grant_type=authorization_code&code=the_signed_jwt_token_you_created
3. Upon successful response you should have a access token and a refresh token.
4. Copy the refresh_token, you will need it to test the refresh_token grant.

Test refresh token grant:
1. Make a post request to https://your_aws_env_url/dev/auth/token?grant_type=refresh_token&refresh_token=valid_refresh_token
2. Successful response should contain a new pair of access and refresh token

## Additional notes
Changes will have to be made in the bankid service and the app in order to support this improved authorization/authentication flow.

To add extra security in this flow we can also add query params that verifies the client sending authorization request srequest, these can be done with the client_id and client_secret params defined in the Oauth documentation.

2021-01-13 12:56 UTC, jwinding reviewed
Still have to test it, but from quickly looking at the code I have a few suggestions.

2021-01-13 12:56 UTC, jwinding commented on libs/token.js
> +// import { throwError } from '@helsingborg-stad/npm-api-error-handling';
remove comment.

2021-01-13 12:56 UTC, jwinding commented on services/auth/token/lambdas/generateToken.js
> +async function validateAutorizationQueryStringParams(params) {
fix spelling error: Autorization --> Authorization

2021-01-13 12:56 UTC, jwinding commented on services/auth/token/lambdas/generateToken.js
> +  const valid_grant_types = ['refresh_token', 'authorization_code'];
Why snake case all of a sudden? change to validGrantTypes.

2021-01-13 12:56 UTC, jwinding commented on libs/token.js
> +  jsonToSign.exp = parseInt(Date.now() / 1000) + expireTimeInSeconds * 60;
You say expireTimeInSeconds, but then you multiply it with 60, so it should probably be expireTimeInMinutes, no?

2021-01-13 12:56 UTC, jwinding commented on services/auth/token/lambdas/generateToken.js
> +async function generateToken(secretConfig, personalNumber, expiresInSeconds) {
Same thing here, expiresInSeconds should probably be expiresInMinutes

2021-01-13 14:11 UTC, dannil76 commented on services/auth/token/lambdas/generateToken.js
> +  if (queryStringParamsError) return response.failure(queryStringParamsError);
Skriv gärna if-satser enligt:
`if (condition) {
  expression
}`

Alltså med måsvingar. Blir konsekvent med vad vi gör i övrig kod på Works

2021-01-13 14:11 UTC, dannil76 commented on services/auth/token/lambdas/generateToken.js
> -    validateEventBody(jsonBody, validateTokenRequestBody)
Body i jsonBody är onödigt. json är väl bra nog? Alltså skippa prefix i alla lägen.

2021-01-13 14:11 UTC, dannil76 commented on services/auth/token/lambdas/generateToken.js
> +  const accessTokenExpiresInMinutes = 20;
om det är en konst kanske vi ska skriva den med versaler för att särskilja dessa från vanliga variabler.

2021-01-13 14:11 UTC, dannil76 commented on services/auth/token/lambdas/generateToken.js
> +function getGrantTypeDetails(queryStringParams) {
...Details är något irrelevant... :)

2021-01-13 14:11 UTC, dannil76 commented on services/auth/token/lambdas/generateToken.js
> +      secretsConfig: authSecrets.authorizationCode,
inte helt tydligt för mig att authSecrets innehåller konfig-stuff....

2021-01-13 14:11 UTC, dannil76 commented on services/auth/token/lambdas/generateToken.js
> + * @param {object} params an object consiting of key/value pairs for query string parameters.
hmm... ajabaja

2021-01-13 14:11 UTC, dannil76 commented on services/auth/token/serverless.yml
> +                refresh_token: true
snake case?!

2021-01-13 14:18 UTC, dannil76 requested changes
Lite kvar

2021-01-13 14:33 UTC, TeddyAndersson commented on services/auth/token/serverless.yml
> +                refresh_token: true
Det är för query string parametrar. Vilket jag anser vara vanligt, dessutom är det vad Oauth standarden har definerat.

2021-01-13 14:36 UTC, TeddyAndersson commented on services/auth/token/lambdas/generateToken.js
> +    validateAutorizationQueryStringParams(event.queryStringParameters)
Förstår inte helt vad du menar här @dannil76.
event.queryStringParameters är något som vi får från lambda argumenten. Ogillar du att jag har förkortat det till Params  i andra variabler?

2021-01-13 14:37 UTC, TeddyAndersson commented on services/auth/token/lambdas/generateToken.js
> -    validateEventBody(jsonBody, validateTokenRequestBody)
Denna kod är inte aktuell

2021-01-13 14:39 UTC, TeddyAndersson commented on services/auth/token/lambdas/generateToken.js
> +  const accessTokenExpiresInMinutes = 20;
Nej det tycker inte jag, lintern kommer klaga direkt om du försöker använda const som en let eller var. Så ser inte detta som ett problem. Däremot om vi har globala konstanter bör de vara med versaler, enligt mitt tycke

2021-01-13 14:40 UTC, TeddyAndersson commented on services/auth/token/lambdas/generateToken.js
> +function getGrantTypeDetails(queryStringParams) {
Anledningen till att jag la till Details är för att du hämtar detaljer som gäller en viss granType, anser alltså inte att du hämtar en grantType i sig själv :)

2021-01-13 14:41 UTC, TeddyAndersson commented on services/auth/token/lambdas/generateToken.js
> +      secretsConfig: authSecrets.authorizationCode,
Här kanske man borde använda versaler typ CONFIG_AUTH_SECRETS

2021-01-13 14:43 UTC, jwinding commented on services/auth/token/lambdas/generateToken.js
> +  const accessTokenExpiresInMinutes = 20;
Håller definitivt med Teddy här. Alla variabler som kan vara const ska vara const, och alla variabler ska vara camelCase, med undantaget globala variabler som kan vara all-caps.

2021-01-13 15:07 UTC, TeddyAndersson commented on services/auth/token/lambdas/generateToken.js
> + * @param {object} params an object consiting of key/value pairs for query string parameters.
Har vi kommit fram till om vi ska använda JSDoc eller inte? Känner mig lite kluven här

2021-01-13 18:59 UTC, dannil76 requested changes

2021-01-13 18:59 UTC, dannil76 commented on services/auth/token/lambdas/generateToken.js
> +  const accessTokenExpiresInMinutes = 20;
Fattar ingenting av vad du @TeddyAndersson skriver?! Jag som är otydlig?

const som let var?? Var kommer det ifrån?!

Nej, menar givetvis `const ACCESS_TOKEN_EXPIRES_IN_MINUTES = 20;`

2021-01-13 19:03 UTC, dannil76 commented on services/auth/token/lambdas/generateToken.js
> +function getGrantTypeDetails(queryStringParams) {
getGrantTypeValues

2021-01-14 11:24 UTC, dannil76 approved these changes
Magi!

2021-01-14 15:27 UTC, jwinding approved these changes
It works (after adding x-api-key to headers 😄 )!

2021-01-15 08:47 UTC, TeddyAndersson commented
Passing query string params have been replaced in favour for passing json payload in the request body. 
The request body that should be passed:
```
// Authorization Code Grant
{
  "grant_type": "authorization_code",
  "code": "a_valid_authorization_code",
}

// Refresh Token Grant
{
  "grant_type": "refresh_token",
  "code": "a_valid_refresh_token",
}
```

2021-01-15 09:28 UTC, jwinding approved these changes
Tested it after the changes, and it works, and we get nice, understandable error messages from the validation; nice that you use JOI for that, we should adopt that for all our request format validation. So, good job, approved!

2021-01-15 11:49 UTC, dannil76 requested changes

2021-01-15 11:49 UTC, dannil76 commented on services/auth/token/helpers/schema.js
> +const jwt = Joi.string().regex(/^[A-Za-z0-9-_]+\.[A-Za-z0-9-_]+\.[A-Za-z0-9-_.+/=]*$/);
Här vore det trevligt med en kommentar till vad regexet matchar på...

2021-01-15 11:49 UTC, dannil76 commented on services/auth/token/lambdas/generateToken.js
> +  const [parseJsonError, parsedJsonData] = await to(parseJsonData(event.body));
...JsonData... hmm ...Data = brus. Allt är väl data?

2021-01-15 11:49 UTC, dannil76 commented on services/auth/token/lambdas/generateToken.js
> +    throwError(400, error.message.replace(/"/g, "'"));
en liten kommentar till vad replace ersätter. Nu måste jag tänka...

2021-01-15 11:49 UTC, dannil76 commented on services/auth/token/lambdas/generateToken.js
> +async function parseJsonData(data) {
data data data data data data data data data data data data data data data data data data data data data data data data data data data data data data data data data data data data data data data data data data data data data data data data data data data data data data data data data data data data data data data data data data data data. Vad är data?!

2021-01-15 12:49 UTC, TeddyAndersson commented on services/auth/token/lambdas/generateToken.js
> +  const [parseJsonError, parsedJsonData] = await to(parseJsonData(event.body));
parsedEventBody?

2021-01-15 13:35 UTC, TeddyAndersson commented
> Tested it after the changes, and it works, and we get nice, understandable error messages from the validation; nice that you use JOI for that, we should adopt that for all our request format validation. So, good job, approved!

Yeah Joi is nice and very flexible. We actually have it implemented on one or two endpoints in the case service already, but far from all services have this validation check :)
So there is an improvement to be done in future sprints for sure! :D

2021-01-15 13:55 UTC, dannil76 approved these changes

2021-01-15 15:14 UTC, merged