Feat/check viva completion
helsingborg-stad/helsingborg-io-sls-api pull request #161
Opened 2021-02-25 22:23 UTC by TeddyAndersson

## Explain the changes you’ve made
Added support for updating a case with correct data when the application status in viva is set to require completion (Stickprov).

## Explain why these changes are made
These changes handels updating of a submitted case when viva needs an applicant to pass additional completion information.

## Explain your solution
This includes handling events for when a viva application is successfully submitted, checking if the application status is set to require completion and updating the case with information in order to start a completion process.

## How to test the changes?

**Setup environment**
1. Checkout this branch.
2. Deploy the vivams service.
3. Add a new test user with the personal number 196001198685 (Vera Toth)
4. Add a new case for this user.
5. Open up CloudWatch for the checkCompletion Lambda in the AWS console

**Setup event to send**
1. Go to the EventBridge in AWS and prepare to send a new event (EventBridge -> eventbuses -> default -> send event) 
2. Add the following input in the send event view:
Event Source: vivams.submitApplication
Detail Type: vivamsSubmitApplicationSuccess
Event detail: {
	"hashedPersonalNumber": "a_hashed_personal_numer",
	"caseKeys": {
		"PK": "pk_for_case",
		"SK": "sk_for_case"
	}
}

**Scenario One**
Send an event on any user that does not have any completion to fullfill (Anyone except Vera Toth).

Result: The case should not update currentFormId or the status

**Scenarion Two**
Send an event on Vera Toth that should have an ongoing completion.

Result: The case should update the currentFormId and the status on the case.

## Anyhting else? (optional)
If you rather have a review in person or have problem with setting up the test environment, just send me a message.

2021-02-26 07:09 UTC, dannil76 requested changes
snakkes!

2021-02-26 07:09 UTC, dannil76 commented on services/viva-ms/lambdas/checkCompletion.js
> +      ':formId': formId,
kanske ska vara konsekvent och skriva currentFormId hela vägen?
completionStatus anväder du hela vägen :)

2021-02-26 07:09 UTC, dannil76 commented on services/viva-ms/lambdas/createVivaCase.js
> +    getApplicationStatus(hahsedPersonalNumber, vadaSSMParams)
kanske det går att få bort argument fler än en?
ex. SSPparams skulle ju kunna ligga i helpern?

2021-02-26 07:09 UTC, dannil76 commented on services/viva-ms/lambdas/submitApplication.js
> +async function getApplicationRequestBody(caseItem, personalNumberHashEncoded) {
hmm. återigen ett argument för mycket enligt mig.
varför är ssm params inte ok här?

2021-02-26 07:09 UTC, dannil76 commented on services/viva-ms/serverless.yml
> +              - vivams.submitApplication
vivams....kanske viva-ms för att spegla servicenamnet?

2021-02-26 08:05 UTC, helsingborgsstad commented
Task linked: [CU-d0zj9g Användaren ska få statusuppdatering om hen är uttagen till stickprov](https://app.clickup.com/t/d0zj9g)

2021-02-26 09:50 UTC, TeddyAndersson commented on services/viva-ms/lambdas/checkCompletion.js
> +  console.log(caseItem);
Kanske är onödig, men tänkte slänga en log så att man vet att allting har gått fint. Kanske borde vara lite mer utförlig dock.

2021-02-26 09:52 UTC, TeddyAndersson commented on services/viva-ms/serverless.yml
> +              - vivams.submitApplication
kanske vivaMs så att vi följer camelCase?

2021-03-01 13:26 UTC, dannil76 approved these changes

2021-03-01 13:45 UTC, dannil76 commented
Dubbelkolla så att rätt formId blir valt :)

2021-03-04 18:57 UTC, dannil76 approved these changes

2021-03-05 09:30 UTC, merged