Feat/submit completion
helsingborg-stad/helsingborg-io-sls-api pull request #167
Opened 2021-03-10 16:43 UTC by TeddyAndersson

## Explain the changes you’ve made
Added support for posting case answers to the viva adapter for a completion form.

## Explain why these changes are made
So that we can send a completion data from a case to viva through the viva adpater.

## Explain your solution
The main logic for this new lambda is to convert case form answers to the data format that our viva adapter expects and post that data to it's completions endpoint (vadaurl/applications/hash_id/completions).

When we convert the answers we do a couple of things:
1. Match tags (answer.field.tags) on a answer to allowed attachment categories ('expenses', 'incomes', 'completion'), if the tagging is wrong the values (filedata) in the answer will not be processed.
2. Retrieve the corresponding file from s3 based on data present in an answer value.
3. Create the attachment object with file binary data (base64), file category etc.

If the creation of the attachment array from answers is successful we make a post request to the viva adapter, the adapter then communicate with viva and append the files/attachment to the workflow

## How to test the changes?

**OBS!**
For this to work with viva, the user being used must be a user that is allowed to submit a completion on a case in viva.
@dannil76 can help you with the user setup. 

**Services:**
Deploy the _viva-ms_ service to your AWS sandbox.
Make sure your _user-api_ service is deployed. (We need the attachment endpoint to upload images/files)

**SSM Params:**
_vadaEnvs_ and _vivaCaseEnvs_ need to be present.

**S3:**
Make sure the user attachment bucket from the resource repo is deployed.

TEST WITH APP:
Go through a completion form and submit it (stickprov).

TEST IN AWS:
1. Upload images to the user attachment bucket through the endpoint users/me/attachments
2. Create a new case in DynamoDB with the test data provided further down, make sure to replace placeholder values.
3. Update the status type in the case to active:submitted:viva
4. Confirm that the lambda has run without errors in CloudWatch (search for: submitCompletion)

TEST DATA FOR DYNAMODB:
{
  "createdAt": 1612515760317,
  "currentFormId": "YOUR_COMPLETION_FORM_ID",
  "details": {
    "administrators": [ ],
    "period": {
      "end": 1614470400000,
      "start": 1612137600000
    },
    "workflowId": "REPLACE_WITH_WORKFLOW_ID_FOR_ACTIVE_WORKFLOW_IN_VIVA"
  },
  "forms": {
    "YOUR_RECURRING_FORM_ID": {
      "answers": [ ], 
      "currentPosition": {
        "currentMainStep": 1,
        "currentMainStepIndex": 0,
        "index": 0,
        "level": 0
      }
    },
    "YOUR_COMPLETION_FORM_ID": {
      "answers": [
        // Feel free to add more fields
        {
          "field": {
            "id": "addRent",
            "tags": [
              "attachment",
              "viva",
              "category",
              "incomes" // this tag value can be one of the following: incomes, expenses or completion
            ]
          },
          "value": [
            {
              // test data for none existing files
              "filename": "does_not_exist.jpg",
              "uploadedFileName": "not_uploaded_file"
            },
            {
              "filename": "test_1.jpg",
              "uploadedFileName": REPLACE_WITH_S3_GENERATED_FILE_NAME
            }
          ]
        },
       {
          "field": {
            "id": "skipThisAnswer",
            "tags": [
              "not_a_valid_tag",
              "skip_this_answer"
            ]
          },
          "value": [
            {
              "filename": "test_1.jpg",
              "uploadedFileName": REPLACE_WITH_S3_GENERATED_FILE_NAME
            }
          ]
        }
      ],
      "currentPosition": {
        "currentMainStep": 1,
        "currentMainStepIndex": 0,
        "index": 0,
        "level": 0
      }
    }
  },
  "id": "9a939342-acc5-4357-bea4-4b4708991234",
  "PK": "USER#REPLACE_WITH_USER_PERSONALNUMBER",
  "provider": "VIVA",
  "SK": "USER#REPLACE_WITH_USER_PERSONALNUMBER#CASE#9a939342-acc5-4357-bea4-4b4708991234",
  "status": {
    "description": "Du måste komplettera din ansökan med bilder som visar dina utgifter och inkomster. Vi behöver din komplettering inom 4 dagar för att kunna betala ut pengar för perioden.",
    "name": "Stickprovskontroll",
    "type": "active:completionRequired:viva"
  },
  "updatedAt": 1612515760317
}

## Was this feature tested in the following environments?
- [X] AWS personal sandbox env.

## Additional thoughts
When retrieving files from a S3 bucket, S3 requires a fileKey. This fileKey should preferable be saved on values in form answers, now we only save the filename of the uploaded file (uploadedFIleName). This requires the lambda to create the fileKey in order to retrieve the file from S3. 
I do not know what s3 returns to the app when a file is uploaded, but if the fileKey is returned we should pass it to avoid stitching it back together in the lambda.

2021-03-11 10:48 UTC, helsingborgsstad commented
Task linked: [CU-ch1k1b Kunna skicka filer till VADA när ansökan har rätt status. Attachment lambda - viva-ms](https://app.clickup.com/t/ch1k1b)

2021-03-11 22:19 UTC, dannil76 requested changes

2021-03-11 22:19 UTC, dannil76 commented on services/viva-ms/serverless.yml
> +                        S: [{ "prefix": "active:submitted:viva" }]
sls deploy giving me error about wrong indentation :)
![Skärmavbild 2021-03-11 kl  23 16 10](https://user-images.githubusercontent.com/768077/110862817-1a35d780-82c0-11eb-9e0d-f15c4b9da38e.png)

2021-03-12 13:18 UTC, dannil76 approved these changes

2021-03-12 13:29 UTC, merged