Fix/user create event flow
helsingborg-stad/helsingborg-io-sls-api pull request #215
Opened 2021-09-01 10:15 UTC by dannil76

## Feature description
When the user logs in via the app for the first time the user is created in the users table (DynamoDb).
Viva-ms needs to ensure that the user indeed is created before it can create a new (open) application period.

## Solution description
New lambda - users-ms/findUser is added to check if logged in user exists in the users table.
If no - findUser emits an event to inform that the user could not be found.

The lambda - users-ms/createUser is configured to trigger if findUser does not find the user and will add the user to the users table.
createUser emits an event to inform that the user is added in the users table.

findUser is configured to trigger if a user has been added in the users table.
findUser is executed once again and will find the user.

If yes - findUser emits an event to inform that the user exists.
viva-ms/createVivaCase configured to trigger on the user exists event emitted by users-ms/findUser

## What areas is affected by these changes?.
users-ms/findUser, users-ms/createUser, viva-ms/createVivaCase. serverless.yml is altered in order to create the necessary event flow and logic

## How to test
Check out this branch.
Redeploy services users-ms and viva-ms.

Test 1
Delete the user Ylva Jansson (195809262743) from the users table
Delete all cases related to Ylva in the cases table
Trigger bankId.collect by executing the script found in mock/putevent.sh

Test 2
Delete all cases related to Ylva in the cases table
Trigger bankId.collect once again to ensure that a new case is created for Ylva

The expected result should follow the flow explained above.

One more thing. There need to be an open period for application for Ylva in Viva-admin.
At the time of writing, there is a period open for application. May disappear, however, as Maria tests.

## Was this feature tested in the following environments?
- [x] Your personal AWS environment.

2021-09-01 10:16 UTC, helsingborgsstad commented
Task linked: [CU-nzdyk6 När sökande loggar in för första gången visas inga ärenden](https://app.clickup.com/t/nzdyk6)

2021-09-01 14:15 UTC, TeddyAndersson requested changes

2021-09-01 14:15 UTC, TeddyAndersson commented on services/users-ms/lambdas/findUser.js
> +    const [emitEventError] = await to(emitEventUserNotFound(userDetail));
To keep the code consistent i would suggest to build on the putEvent naming convention, emitEvent is a new naming for the same functionality. This made me a bit confused, due to the knowledge of our putEvent function from the libs.

putEvent in itself might not be the best name for this function but it is what is used currently, so would be good if we could stick to that for know :)

2021-09-01 14:15 UTC, TeddyAndersson commented on services/users-ms/lambdas/findUser.js
> +}
These functions feels very clear in their purpose but at the same time redundant, do not have any suggestions for other solutions at this moment but there is room for improvement i guess :)

2021-09-01 14:15 UTC, TeddyAndersson commented on services/users-ms/lambdas/findUser.js
> +async function getUser(personalNumber) {
This code block feels familiar, are we not doing this action towards dynamoDb elsewhere? If so we have multiple functions in different places that has the same task :)

2021-09-01 14:15 UTC, TeddyAndersson commented on services/users-ms/lambdas/findUser.js
> +async function getUser(personalNumber) {
Ie we then have redundancy in the code.

2021-09-02 11:20 UTC, TeddyAndersson commented on services/users-ms/lambdas/findUser.js
> +}
A thought on these functions might be to declare them in an object

```JS
const userEvents = {
  exists: async (user) => putEvent(user, ...),
  notFound: async (user) => putEvent(user, ...)
}

// then we use them like this
const eventResponse = userEvent.exists(user)
const eventResponse = userEvent.notFound(user)
```
You could also go further and do something like
```JS
// extend the incoming user object with functions/methods
const user = {
  ...user, 
  event: {
    send: (type) => putUserEvent(user, type) // don't now if there is a better way of referring to the user object here, but you get my intention
  }
}

async function putUserEvent(user, type) {
  const eventTypeCollection = {
   notFound: {...},
   exists: {...},
  }

  return await putEvent(...eventTypeCollection[type])
}

user.event.put('exists') 
```

2021-09-02 14:56 UTC, TeddyAndersson approved these changes

2021-09-02 14:57 UTC, merged