Fix/reset signatures on completion
helsingborg-stad/helsingborg-io-sls-api pull request #217
Opened 2021-09-09 11:40 UTC by jonatanhanson

Fixed bug where cases with status "completion required" gets wrong status when they are "ongoing". 
Read more here: https://app.clickup.com/t/n7fq0p

This is fixed by resetting applicants signature to "false", when the case is being updated with completion status. 
Also needed to change some status conditions to handle cases with co-applicants.

2021-09-09 11:41 UTC, helsingborgsstad commented
Task linked: [CU-n7fq0p När användare avbryter stickprov i appen sätts status till inskickad](https://app.clickup.com/t/n7fq0p)

2021-09-09 15:02 UTC, dannil76 requested changes

2021-09-10 12:05 UTC, jonatanhanson commented on services/viva-ms/lambdas/checkCompletion.js
> +    throwError(error.statusCode, error.message);
fixed now

2021-09-14 13:07 UTC, KenthLjungHBG approved these changes
Tested in sandbox by mocking a completion to be required. Seems to work as intended! 🙂

2021-09-15 11:54 UTC, dannil76 approved these changes

2021-09-15 12:04 UTC, merged