Fix/bounced event flow
helsingborg-stad/helsingborg-io-sls-api pull request #274
Opened 2021-11-22 19:05 UTC by dannil76

## Explain the changes you’ve made
The submittCompletion fired on occasions when it should not. This is due to that the status ("active:submitted") is set on several occasions throughout a case's life-span, but the completion should only be sent once when state is "VIVA_COMPLETION_REQUIRED" and the status is "active:submitted".

2021-11-22 19:06 UTC, sebastianthulin commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-check.svg) Quality gate: **_Passed_** 
 


            
 ![No issues](https://app.embold.io/assets/images/svg/check-circle.svg) Everything looks good
 [Details](https://app.embold.io/organization/gh/helsingborg-stad/repositories/602c13c73b93a7537d767e421a43afaa/pull-request/274)

2021-11-23 08:23 UTC, helsingborgsstad commented
Task linked: [CU-1m3n75d Bugg: dokument för stickprov laddas upp dubbelt i Viva](https://app.clickup.com/t/1m3n75d)

2021-11-23 10:45 UTC, TeddyAndersson requested changes

2021-11-23 10:45 UTC, TeddyAndersson commented on services/viva-ms/serverless.yml
> +              state: ["VIVA_COMPLETION_REQUIRED"]
Fix Indentation to keep serverless happy

2021-11-23 10:45 UTC, TeddyAndersson commented on services/viva-ms/lambdas/submitCompletion.js
> +  const [getCaseItemError, { Item: caseItem }] = await getStoredUserCase(
There are no checks to see if the returned Item is empty. IE what happens if the query is successful but the data returned is empty.

2021-11-23 14:09 UTC, MasterKenth approved these changes

2021-11-23 14:10 UTC, MasterKenth commented
I haven't tested this but it seems fine.

2021-11-23 14:13 UTC, TeddyAndersson reviewed
Ship it! 🚀

2021-11-23 14:19 UTC, merged