Feat/completions set case attributes
helsingborg-stad/helsingborg-io-sls-api pull request #292
Opened 2021-12-29 17:48 UTC by dannil76

2021-12-29 17:49 UTC, sebastianthulin commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-check.svg) Quality gate: **_Passed_** 
 


            
 ![No issues](https://app.embold.io/assets/images/svg/check-circle.svg) Everything looks good
 [Details](https://app.embold.io/organization/gh/helsingborg-stad/repositories/602c13c73b93a7537d767e421a43afaa/pull-request/292)

2021-12-29 17:55 UTC, helsingborgsstad commented
Task linked: [CU-1nwtvxr Uppdatera status på ärende till "Ansökan behöver kompleteras"](https://app.clickup.com/t/1nwtvxr)

2021-12-29 17:56 UTC, helsingborgsstad commented
Task linked: [CU-1nwtvxr Uppdatera status på ärende till "Ansökan behöver kompleteras"](https://app.clickup.com/t/1nwtvxr)

2022-01-04 15:08 UTC, karlknowit requested changes

2022-01-04 15:08 UTC, karlknowit commented on services/viva-ms/serverless.yml
> +  eventBridge:
are you sure that `eventBridge` is a property in serverless provider? It is not in their documentation.

2022-01-04 15:08 UTC, karlknowit commented on services/viva-ms/lambdas/checkCompletionsStatus.js
> +/* eslint-disable no-console */
Missing tests for this lambda function

2022-01-04 15:08 UTC, karlknowit commented on services/viva-ms/lambdas/setCaseCompletions.js
> +
Missing tests for this lambda function

2022-01-12 14:15 UTC, dannil76 commented on services/viva-ms/lambdas/setCaseCompletions.js
> +import to from 'await-to-js';
will extract to helpers

2022-01-12 14:16 UTC, dannil76 commented on services/viva-ms/lambdas/setCaseCompletions.js
> +  const { persons } = caseItem;
Probably not :)
This could even be it's own lambda?

2022-01-12 14:17 UTC, dannil76 commented on services/viva-ms/lambdas/checkCompletionsStatus.js
> +/* eslint-disable no-console */
Please help me.. :)

2022-01-12 18:34 UTC, helsingborgsstad commented
Task linked: [CU-1nwtvxr Uppdatera status på ärende till "Ansökan behöver kompleteras"](https://app.clickup.com/t/1nwtvxr)

2022-01-13 10:22 UTC, karlknowit approved these changes

2022-01-13 14:08 UTC, merged