Feat/completions check
helsingborg-stad/helsingborg-io-sls-api pull request #295
Opened 2021-12-29 17:59 UTC by dannil76

2021-12-29 17:59 UTC, sebastianthulin commented
![Quality gate](https://app.embold.io/assets/images/svg/shield-check.svg) Quality gate: **_Passed_** 
 


            
 ![No issues](https://app.embold.io/assets/images/svg/check-circle.svg) Everything looks good
 [Details](https://app.embold.io/organization/gh/helsingborg-stad/repositories/602c13c73b93a7537d767e421a43afaa/pull-request/295)

2022-01-04 14:28 UTC, karlknowit requested changes

2022-01-04 14:28 UTC, karlknowit commented on services/viva-ms/lambdas/checkCompletionsStatus.js
> +    return false;
instead of returning false, shouldn't we return a correct api-gateway response?

2022-01-04 14:28 UTC, karlknowit commented on services/viva-ms/lambdas/checkCompletionsStatus.js
> +  const completionStatusCodes = [64, 128, 256, 512];
Im not fond of having "dangling" values like 64 .. etc. Can this be put in a constant instead like:

```js
// in constant file
const VIVA_STATUS_CODE = {
  COMPLETION_REQUIRED: 64,
  CASE_EXIST: 128,
  APPLICATION_ACTIVATED: 256,
  E_APPLICATION_ALLOWED: 512
}
```
```js
// in checkCompletionsStatus.js
const { VIVA_STATUS_CODE } from "../some_constant_file";

const completionStatusCodes = Object.values(VIVA_STATUS_CODE);


export async function main(event, context) { 
  ...

  const hasInvalidStatusCodeCombination = !validateApplicationStatus(applicationStatusList, completionStatusCodes);

if (hasInvalidStatusCodeCombination) { ... }

}

...

log.info(
      `No Viva completion status(${VIVA_STATUS_CODE.COMPLETION_REQUIRED}) found`,
      context.awsRequestId,
      'service-viva-ms-checkCompletionsStatus-002',
      applicationStatusList
    );
```

2022-01-12 14:06 UTC, closed without merging