add put event
helsingborg-stad/helsingborg-io-sls-api pull request #344
Opened 2022-02-22 14:39 UTC by dannil76

## Explain the changes you’ve made
Let cases-api getCaseList put an event and make viva-ms applicationStatus react on it.
This makes it possible for the app to retrigger the viva (create case) flow by manualy refreshing the cases list

## Explain why these changes are made
These changes makes the user in charge of when the viva case it initiated instead of relying on login

## Explain your solution
Add event in the cases-api/getCasesList lambda whom will put an event every time the cases list is retrived.
viva-ms/applicationStatus is then triggered on this event instead of the previous event sent from users-ms/findUser lambda

## How to test
1. Checkout this branch
2. run `sls deploy` within service folder for `viva-ms` and `cases-api`
3. Make sure you have an Viva user that is allowed to apply
4. Remove all user cases from dynamodb cases table
5. Login with the app
6. One 'open' case should be listed
7. Delete this case from the cases table in dynamodb
8. Refresh the cases list on the app by draging your fingre from the top of the screen in an downward move.
9. A new 'open' case shuould be listed

## Tested environments

- [x] Your personal AWS environment.
- [x] App 

## Checklist for reviewers

Here are a few points that are useful for reviewers to check.

The short list of the (maybe) most important points are:

- Does this PR work as expected?
- Does the PR properly only concern a single feature/bug/thing?
- Is the code clear and concise?
- Will the changes impact existing functionality?
- Are there any linting errors (ESLint) that should be resolved?
- Do the automatic GitHub checks pass?

However it is good if a reviewer can be as thorough as possible,
within reasonable limits of course.

### Functionality

- Does this PR work as expected?
- If this is a new feature, does it add value, or is it a sign of feature-creep?
- Will the changes impact existing functionality?
- Does the changes create inconsistencies somewhere else?
- Does the code work on different platforms if applicable?
- How does the code handle if unexpected values are passed to functions etc.?

### Readability, syntax, formatting, style

- Is the code clear and concise?
- Has styling rules (Prettier) been applied to included files?
- Are functions/variables/etc. aptly named?

### Design

- Is the code properly planned and designed?
- Is code organized/separated in a logical fashion?
- Does the code follow clean code practices to a reasonable degree?
- Is the code self-documenting enough?
- Is the code in sync with existing patterns/technologies?
- Does the code reuse existing functionality where applicable?
- Is the code designed with reusability in mind?
- Does the code have hard-coded values that can be refactored?

### Patterns, idioms, tests, best practices

- Are there any linting errors (ESLint) that should be resolved?
- Is the code properly typed (TypeScript)?
- Does the code utilize language features to their full potential?

### Debugging, testing, configuring

- Is appropriate logging used?
- Have tests been added/modified to accommodate the changes?
- Is the feature sufficiently configurable in case tweaks are required in the future?

### Performance, reliability, scalability

- Is the code well optimized?
- Does the code scale?
- Does the code handle failure scenarios?

### Security

- Is there any obvious potential for exploits and security threats?
- Does code check proper authorization where applicable?

### Etiquettes

- Are commits atomic (does only one thing per commit)?
- Does the PR properly only concern a single feature/bug/thing?
- Are commit messages well-written?
- Do the automatic GitHub checks pass?

2022-02-22 14:40 UTC, helsingborgsstad commented
Task linked: [CU-1xrhapk Bugg: Användare ser inga ärenden när dom loggar in i appen](https://app.clickup.com/t/1xrhapk)

2022-02-23 08:25 UTC, MasterKenth requested changes
Works but also creates several cases when refreshing quickly (race condition).

2022-02-24 14:45 UTC, MasterKenth approved these changes
We'll have to monitor how this holds up during real world situations.

2022-02-24 14:50 UTC, karlknowit approved these changes

2022-02-24 14:52 UTC, merged