feat: add lambda code snippet to vs
helsingborg-stad/helsingborg-io-sls-api pull request #378
Opened 2022-04-11 11:15 UTC by petter-a

While creating a new javascript file, type lambda and use autocomplete to add a boilerplate for a lambda.

2022-04-11 13:39 UTC, dannil76 approved these changes

2022-04-12 13:26 UTC, kajm requested changes

2022-04-12 13:26 UTC, kajm commented on .vscode/javascript.code-snippets
> +{
Aren't we missing `context` ?

2022-04-26 07:58 UTC, kajm approved these changes

2022-04-26 08:43 UTC, merged