Fix/completions
helsingborg-stad/helsingborg-io-sls-api pull request #400
Opened 2022-05-12 14:27 UTC by dannil76

## Explain the changes you’ve made
Updated status text to complete the completions work flow

## Tested environments

- [x] Your personal AWS environment.

---

## Checklist for reviewers

Here are a few points that are useful for reviewers to check.

The short list of the (maybe) most important points are:

- Does this PR work as expected?
- Does the PR properly only concern a single feature/bug/thing?
- Is the code clear and concise?
- Will the changes impact existing functionality?
- Are there any linting errors (ESLint) that should be resolved?
- Do the automatic GitHub checks pass?

However it is good if a reviewer can be as thorough as possible,
within reasonable limits of course.

### Functionality

- Does this PR work as expected?
- If this is a new feature, does it add value, or is it a sign of feature-creep?
- Will the changes impact existing functionality?
- Does the changes create inconsistencies somewhere else?
- Does the code work on different platforms if applicable?
- How does the code handle if unexpected values are passed to functions etc.?

### Readability, syntax, formatting, style

- Is the code clear and concise?
- Has styling rules (Prettier) been applied to included files?
- Are functions/variables/etc. aptly named?

### Design

- Is the code properly planned and designed?
- Is code organized/separated in a logical fashion?
- Does the code follow clean code practices to a reasonable degree?
- Is the code self-documenting enough?
- Is the code in sync with existing patterns/technologies?
- Does the code reuse existing functionality where applicable?
- Is the code designed with reusability in mind?
- Does the code have hard-coded values that can be refactored?

### Patterns, idioms, tests, best practices

- Are there any linting errors (ESLint) that should be resolved?
- Is the code properly typed (TypeScript)?
- Does the code utilize language features to their full potential?

### Debugging, testing, configuring

- Is appropriate logging used?
- Have tests been added/modified to accommodate the changes?
- Is the feature sufficiently configurable in case tweaks are required in the future?

### Performance, reliability, scalability

- Is the code well optimized?
- Does the code scale?
- Does the code handle failure scenarios?

### Security

- Is there any obvious potential for exploits and security threats?
- Does code check proper authorization where applicable?

### Etiquettes

- Are commits atomic (does only one thing per commit)?
- Does the PR properly only concern a single feature/bug/thing?
- Are commit messages well-written?
- Do the automatic GitHub checks pass?

2022-05-12 14:29 UTC, helsingborgsstad commented
Task linked: [CU-2qa1anj Uppdatera statustexter som berör completions](https://app.clickup.com/t/2qa1anj)

2022-05-16 09:44 UTC, kajm requested changes

2022-05-16 09:44 UTC, kajm commented on libs/caseStatuses.js
> +      'Väntar på signering. När båda har signerat med BankID skickas ansökan in för bedömning.',
remove `.`

2022-05-16 09:44 UTC, kajm commented on libs/caseStatuses.js
> +      'Du måste komplettera din ansökan med bilder som visar dina utgifter och inkomster. Vi behöver din komplettering inom 3 dagar för att kunna betala ut pengar för perioden.',
remove `.`

2022-05-16 09:44 UTC, kajm commented on libs/caseStatuses.js
> +      'Tiden för att lämna in bilder har gått ut. Din komplettering är mottagen och handläggs.',
remove `.`

2022-05-16 11:22 UTC, MasterKenth requested changes

2022-05-16 11:22 UTC, MasterKenth commented on libs/caseStatuses.js
> +    description: 'Ansökan är signerad.',
remove `.`

2022-05-16 11:31 UTC, kajm approved these changes

2022-05-16 11:32 UTC, merged