Feat/submit application attachments
helsingborg-stad/helsingborg-io-sls-api pull request #401
Opened 2022-05-19 12:45 UTC by dannil76

## Explain the changes you’ve made
Lagt till stöd för att kunna bifoga dokument tillsammans med ansökan. Detta gör det möjligt för både grund- och löpande ansökan.

## Explain why these changes are made
Sökande ska kunna bifoga dokument tillsammans med sin ansökan för att det ska vara lätt att göra rätt

## Explain your solution
Brutit ut logik som används både för submitCompletion och submitApplication till en helper (attachment.ts)
Lagt till attributet `attachments` till payload för post anropet till VADA

## How to test

1. Checkout this branch
2. run `sls deploy` within service folder for `viva-ms`

## Tested environments

- [x] Your personal AWS environment.

---

## Checklist for reviewers

Here are a few points that are useful for reviewers to check.

The short list of the (maybe) most important points are:

- Does this PR work as expected?
- Does the PR properly only concern a single feature/bug/thing?
- Is the code clear and concise?
- Will the changes impact existing functionality?
- Are there any linting errors (ESLint) that should be resolved?
- Do the automatic GitHub checks pass?

However it is good if a reviewer can be as thorough as possible,
within reasonable limits of course.

### Functionality

- Does this PR work as expected?
- If this is a new feature, does it add value, or is it a sign of feature-creep?
- Will the changes impact existing functionality?
- Does the changes create inconsistencies somewhere else?
- Does the code work on different platforms if applicable?
- How does the code handle if unexpected values are passed to functions etc.?

### Readability, syntax, formatting, style

- Is the code clear and concise?
- Has styling rules (Prettier) been applied to included files?
- Are functions/variables/etc. aptly named?

### Design

- Is the code properly planned and designed?
- Is code organized/separated in a logical fashion?
- Does the code follow clean code practices to a reasonable degree?
- Is the code self-documenting enough?
- Is the code in sync with existing patterns/technologies?
- Does the code reuse existing functionality where applicable?
- Is the code designed with reusability in mind?
- Does the code have hard-coded values that can be refactored?

### Patterns, idioms, tests, best practices

- Are there any linting errors (ESLint) that should be resolved?
- Is the code properly typed (TypeScript)?
- Does the code utilize language features to their full potential?

### Debugging, testing, configuring

- Is appropriate logging used?
- Have tests been added/modified to accommodate the changes?
- Is the feature sufficiently configurable in case tweaks are required in the future?

### Performance, reliability, scalability

- Is the code well optimized?
- Does the code scale?
- Does the code handle failure scenarios?

### Security

- Is there any obvious potential for exploits and security threats?
- Does code check proper authorization where applicable?

### Etiquettes

- Are commits atomic (does only one thing per commit)?
- Does the PR properly only concern a single feature/bug/thing?
- Are commit messages well-written?
- Do the automatic GitHub checks pass?

2022-05-19 12:48 UTC, helsingborgsstad commented
Task linked: [CU-2nw5cf2 SubmitApplication ska kunna skicka med attachments](https://app.clickup.com/t/2nw5cf2)

2022-05-20 07:28 UTC, kajm commented on services/viva-ms/src/helpers/attachment.ts
> +    }
```js
import * as S3 from '../../src/libs/S3';

jest.mock('../../src/libs/S3');

import { createAttachmentFromAnswers } from '../../src/helpers/attachment';

it('just works', async () => {
  jest
    .spyOn(S3.default, 'getFile')
    .mockResolvedValueOnce({
      Body: 'Some body here',
      id: '1',
    })
    .mockRejectedValueOnce({
      Body: 'Another body',
      id: '2',
    });

  const result = await createAttachmentFromAnswers('19949292-1234', [
    {
      field: {
        id: 'field_id',
        tags: [],
      },
      value: [
        {
          uploadedFileName: 'uploadedFileName_1',
        },
        {
          uploadedFileName: 'uploadedFileName_2',
        },
      ],
    },
    {
      field: {
        id: 'field_id',
        tags: [],
      },
      value: 'String value, SHOULD NOT BE ADDED',
    },
  ]);

  console.log('RESULT: ', result);
  expect(result).toBe(true);
});

```

2022-05-20 15:11 UTC, dannil76 commented on services/viva-ms/src/helpers/attachment.ts
> +    }
Will fix it asap

2022-05-24 06:30 UTC, kajm requested changes

2022-05-24 06:30 UTC, kajm commented on services/viva-ms/test/lambdas/submitApplications.test.ts
> +let event: LambdaRequest;
event -> input ?

2022-05-24 08:38 UTC, kajm approved these changes

2022-05-24 08:48 UTC, merged