fix: only use array answers for populating previous answers
helsingborg-stad/helsingborg-io-sls-api pull request #458
Opened 2022-10-19 13:44 UTC by MasterKenth

## Explain the changes you’ve made

Check if previous answers is array (i.e. not encrypted) before using for pre-populating new case.

## Explain why these changes are made

Some edge-cases have previous cases with decisions but with encrypted answers - pre-population then crashes for any new cases.

## How to test

Concrete example:

1. Checkout this branch
2. Have a case with decisions but replace the answers of the form with encrypted answers:

```json
"a1ce65a0-3d7c-11ec-801e-2db8270ee167": {
   "answers": {
    "encryptedAnswers": "abcdefg"
   },
   "currentPosition": {
    "currentMainStep": 4,
    "currentMainStepIndex": 3,
    "index": 3,
    "level": 0,
    "numberOfMainSteps": 9
   },
   "encryption": {
    "encryptionKeyId": "2fa16de5-6557-4f35-bb36-3a475fd9136d",
    "symmetricKeyName": "2fa16de5-6557-4f35-bb36-3a475fd9136d",
    "type": "password"
   }
  }
```

3. Login/refresh to try to create a new case and verify it is created as expected (with no pre-populated answers).

2022-10-19 13:46 UTC, helsingborgsstad commented
Task linked: [CU-26b6gkr Hantera krypterade formulär så att lambdan inte krashar vid förpopulering](https://app.clickup.com/t/26b6gkr)

2022-10-20 15:05 UTC, dannil76 requested changes
Linting gnäller

2022-10-20 15:05 UTC, dannil76 commented on libs/formAnswers.js
> +    const previousAreEncrypted = !Array.isArray(previousCaseAnswers);
Tycker det är bra om vi håller oss till formatet med isVariableName. Missade själv att det stod Are i mitten av ordet.

isPreviousAnswersEncrypted blir väl bra?

2022-10-21 07:53 UTC, MasterKenth commented on libs/formAnswers.js
> +    const previousAreEncrypted = !Array.isArray(previousCaseAnswers);
Kan köra på `isPreviousEncrypted` annars blir det kass engelska eller för verbost.

2022-10-21 11:07 UTC, kajm commented on libs/formAnswers.d.ts
> +}): Record<string, never>;
Can these be typed?

2022-10-25 05:50 UTC, helsingborgsstad commented
Task linked: [CU-3n5jccc Skapa logik som kontrollerar personnnummer mot en lista i ssm-params](https://app.clickup.com/t/3n5jccc)

2022-10-25 08:29 UTC, merged