refactor(uploadattachment): store file under unique id only
helsingborg-stad/helsingborg-io-sls-api pull request #468
Opened 2022-11-04 13:58 UTC by kajm

## Explain the changes you’ve made
Remove the need of filename in body for storing files in S3.

## Explain why these changes are made
The application should only upload files and let the backend store it under its own unique id. The unique upload id is then returned to the client.

## How to test

1. Checkout this branch
2. run `sls deploy` within service folder for `service users-api`
3. Run the endpoint in whatever way you like and check the response

2022-11-04 13:58 UTC, helsingborgsstad commented
Task linked: [CU-3r13qxt Ändra uploadAttachment endpoint att ej hantera filename i URL](https://app.clickup.com/t/3r13qxt)

2022-11-07 12:09 UTC, MasterKenth requested changes

2022-11-07 12:30 UTC, kajm commented on services/users-api/src/lambdas/uploadAttachment.ts
> +  const { mime, personalNumber } = input;
Changed

2022-11-07 12:31 UTC, MasterKenth approved these changes

2022-11-07 12:32 UTC, merged