feat(serverless.yml): update lambda node runtime from 14 to 16
helsingborg-stad/helsingborg-io-sls-api pull request #488
Opened 2022-12-13 07:31 UTC by kajm

## Explain the changes you’ve made
Update lambda node runtime from version 14 to 16

## Explain why these changes are made
To have an updated lambda runtime gives multiple advantages like improved stability and performance.

## How to test

1. Checkout this branch
2. run `sls deploy` within service folder for all services
3. Run application -> OK
4. Run tests -> OK

2022-12-13 10:59 UTC, MasterKenth approved these changes

2022-12-15 09:18 UTC, dannil76 commented
Vilken task var detta?

2022-12-15 09:24 UTC, dannil76 requested changes
Finns det någon anledning till att uppgradera då AWS-SDK version 2.1083.0 endast kräver 14?

Är 100% säkra på att kodbasen är kompatibel med node 16?

2022-12-15 12:50 UTC, kajm commented
> Är 100% säkra på att kodbasen är kompatibel med node 16?

@dannil76 
Känner mig ganska säker på att det fungerar.

<img width="1479" alt="image" src="https://user-images.githubusercontent.com/9610681/207863360-aff7e79d-866f-4bd0-8cf9-a63fe8435589.png">

Kört det några dagar nu utan problem

2022-12-15 15:38 UTC, merged