Fix/allow new application change
helsingborg-stad/helsingborg-io-sls-api pull request #490
Opened 2022-12-14 11:47 UTC by kajm

## Explain the changes you’ve made
Refactored `createNewVivaCase` lambda to not create new viva cases when its not supposed to. Implemented logic which follows the decide chart:

![image](https://user-images.githubusercontent.com/9610681/207586744-0fd4f340-b3aa-4896-9430-131e7b1939e7.png)

## Explain why these changes are made
The grundansökan-button did appear when not supposed to, which meant that a new application case where created. This PR hopefully fixes the issue and avoid creating new application cases when not needed.

## How to test

Concrete example:

1. Checkout this branch
2. run `sls deploy` within service folder for `service viva`
3. Run the EKB application and add a co-applicant before answering the grundansökan form
4. Login as the co-applicant
5. The grundansökan button should not be visible
6. no new cases should either be created in cases table

2022-12-14 11:48 UTC, helsingborgsstad commented
Task linked: [CU-3xjhe0r Bugg: Knapp för grundansökan visas för medsökande](https://app.clickup.com/t/3xjhe0r)

2022-12-15 09:20 UTC, dannil76 requested changes

2022-12-15 17:32 UTC, dannil76 commented
Något som du @kajm tycker är oklart med mina kommentarer? Tänker att min review legat ett tag? :)

2022-12-19 08:30 UTC, dannil76 approved these changes

2022-12-19 08:44 UTC, merged