refactor(openapi): add docs for status messages
helsingborg-stad/helsingborg-io-sls-api pull request #494
Opened 2022-12-21 14:43 UTC by kajm

## Explain the changes you’ve made
Added openapi documentation for status api

## Explain why these changes are made
We want our api:s to be documented, hence creating this openapi docs.

## How to test

1. Checkout this branch
2. Open status-api with VsCode
3. runt the openapi.yml file in swagger

2022-12-21 14:43 UTC, helsingborgsstad commented
Task linked: [CU-3xcre5g Skapa OpenAPI för status service](https://app.clickup.com/t/3xcre5g)

2022-12-23 12:40 UTC, MasterKenth commented on services/status-api/openapi.yml
> +        The list of messages returned in the response could be on of the following:
Should refrain from using suggestive actions I think, so skip the "that would be used..." part and simply just explain how this endpoint works (inputs and outputs).

Could also probably rephrase this to something like "in order of severity:".

2022-12-23 12:41 UTC, MasterKenth commented on services/status-api/openapi.yml
> +      parameters:
This endpoint does not require a JWT (only api key).

2022-12-23 12:42 UTC, MasterKenth requested changes
comments.

2022-12-27 08:25 UTC, MasterKenth approved these changes

2022-12-27 09:14 UTC, merged