Refactor/ekb collector metrics
helsingborg-stad/helsingborg-io-sls-api pull request #504
Opened 2023-01-22 11:43 UTC by dannil76

Dynamicly creates metrics based on status types.

## How to test

Concrete example:

1. Checkout this branch
2. run `sls deploy` within service folder for `service metrics-api` and `viva-ms`
3. add cases to cases table with attributs GSI2PK set to 'CREATED#202301'
4. set attribute status.type to 'notStarted' or eq (look at possible values in libs/constants.js)
5. hit endpoint /metrics/ekb?format=ebnf
6. verify output

2023-01-22 11:44 UTC, helsingborgsstad commented
Task linked: [CU-865bj8waw Refaktorisera collector och skapa metrics från ärenden direkt](https://app.clickup.com/t/865bj8waw)

2023-01-23 12:49 UTC, MasterKenth requested changes
Ser bra ut, bara några små kommentarer.

2023-01-23 12:50 UTC, MasterKenth requested changes
Ser bra ut, bara några små kommentarer.

2023-01-23 18:42 UTC, dannil76 commented on services/metrics-api/src/helpers/cases.ts
> +function casesReducer(
osäker på hur man ska tänka här. som jag tänkte var att funktionsnamnet kunde vara något mer generiskt för att typningen berättar vad som görs?

Men visst det är alltid bra med tydliga namn

2023-01-24 14:53 UTC, MasterKenth approved these changes

2023-01-24 14:53 UTC, merged