fix(createvivacase): use previous case answer instead of applicant info if possible
helsingborg-stad/helsingborg-io-sls-api pull request #515
Opened 2023-02-14 08:39 UTC by MasterKenth

## Explain the changes you’ve made

Prioritized using answers from any previous case over using user information when pre-populating address, phone etc.

## Explain why these changes are made

The last case if any holds the most up-to-date information as the users table info is not updated.

## How to test

Concrete example:

1. Checkout this branch
2. Delete any existing cases and create a new case for an applicant
3. Verify the created case and form have answers for address etc. that matches the info in the users table
4. Fill out the case with a different address and submit
5. Create a new case for the same user
6. Verify the new case form have answers for address etc. that matches the info provided in the last case

2023-02-14 08:41 UTC, helsingborgsstad commented
Task linked: [CU-3n5jkpg Vid ihopslagning av data från Users och formulär, prioritera det som tidigare angivits i formuläret](https://app.clickup.com/t/3n5jkpg)

2023-02-14 08:52 UTC, dannil76 approved these changes

2023-02-15 17:09 UTC, dannil76 requested changes

2023-02-15 17:09 UTC, dannil76 commented on services/viva/microservice/test/lambdas/createVivaCase.test.ts
>    beforeAll(() => {
Behöver du denna? Finns redan på rad 29.

2023-02-16 08:56 UTC, merged