Feat/create case contacts
helsingborg-stad/helsingborg-io-sls-api pull request #521
Opened 2023-03-17 11:56 UTC by MasterKenth

## Explain the changes you’ve made

Read default case contacts from S3 when creating cases.

## Explain why these changes are made

New case structure for managing contacts on a case.

## How to test

Concrete example:

Use [resources PR 130](https://github.com/helsingborg-stad/helsingborg-io-sls-resources/pull/130).

Add a `contacts.json` file in the root of the new config bucket. Sample contents:

```json
[
  {
    "name": "KC",
    "description": "Hej! Ring [Kontaktcenter](tel://0767000000)"
  }
]
```

1. Checkout this branch
2. Create a new viva case via the API (e.g. simulate login for a valid user)
3. Verify contacts are added to the case

2023-03-17 11:56 UTC, helsingborgsstad commented
Task linked: [CU-865bx1q60 Lägg till KC kontakt-information när case skapas (createVivaCase)](https://app.clickup.com/t/865bx1q60)

2023-03-21 09:13 UTC, dannil76 requested changes

2023-03-21 09:13 UTC, dannil76 commented on services/viva/helpers/case/EkbCaseFactory.ts
> +}
Vill man inte dölja Viva-specifika delar här?

2023-03-21 13:00 UTC, dannil76 approved these changes

2023-03-21 13:07 UTC, merged